from typing import Union, Sequence
from alembic import op
import sqlalchemy as sa


revision: str = 'fa3e0711a8c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc',
    sa.Column('btc_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('btc_uuid', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.UniqueConstraint('btc_id'),
    sa.UniqueConstraint('btc_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('btc')
    # ### end Alembic commands ###